name: Lyrid Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install lc and code submit
      run: |
        wget https://api.lyrid.io/client/dl/linux
        ls -A
        mv linux lc
        chmod u+x lc
        ./lc config add --config bahtera --key ${{secrets.ACCESS_KEY}} --secret ${{secrets.SECRET_KEY}}
        ./lc code submit -i RxGCBBMeH2 --no-wait
        sleep 10