name: Lyrid Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install lc and code submit
      run: |
        wget https://api.lyrid.io/client/dl/linux
        ls -A
        mv linux lc
        chmod u+x lc
        ./lc config add --config lyrid-test --key <ACCESS_KEY> --secret <SECRET_KEY>
        ./lc code submit -i RxGCBBMeH2
        sleep 50