name: Lyrid Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install lc and code submit
      env:
        LYRID_ACCESS_KEY: ${{ secrets.LYRID_ACCESS_KEY }}
        LYRID_SECRET_KEY: ${{ secrets.LYRID_SECRET_KEY }}
      run: |
        wget https://api.lyrid.io/client/dl/linux
        ls -A
        mv linux lc
        chmod u+x lc
        ./lc config add --config lyrid-test --key "$LYRID_ACCESS_KEY" --secret "$LYRID_SECRET_KEY"
        ./lc code submit -i RxGCBBMeH2
        sleep 50